[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.typst]
command = "typstyle"
includes = ["*.typ"]
options = ["-i", "--line-width", "190", "--indent-width", "2"]

[global]
excludes = ["docs/refs/**"]
