//! No API. This crate exists for its build script, which derives
//! `aquafix/assets/` from the repo-root `assets/`.
//!
//! It is a separate crate because `aquafix/build.rs` is generated by v_flakes
//! and rewritten on every `nix develop`; anything added there is lost. As a
//! build-dependency of `aquafix`, this one's build script is guaranteed to run
//! before `aquafix` compiles, which is what `asset!()` needs.
