import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { OUTPUT, renderSources } from "../scripts/css-sources";

const root = join(import.meta.dirname, "..");

// `app/sources.css` is generated (`npm run css-sources`) and committed so the
// build runs no step before `next build`. Under `source(none)` it is the only
// way Tailwind sees the uikit's and the marketing layer's class literals: a
// stale copy drops the rules for a newly reached component from the prod CSS
// without any error. This keeps the committed copy honest.
function expectSourcesCurrent(dir: string): void {
  expect(
    readFileSync(join(dir, OUTPUT), "utf8"),
    `${OUTPUT} is stale: run \`npm run css-sources\` and commit the result`,
  ).toBe(renderSources(dir));
}

describe("the Tailwind package sources", () => {
  it("are the generator's output for the app's imports, byte for byte", () => {
    expectSourcesCurrent(root);
  });
});

// A landing in miniature, with stand-ins for the three packages the walk
// follows, so the cases below do not hang on what today's uikit happens to
// export.
const LANDING: Record<string, string> = {
  "proxy.ts": "export {};\n",
  "instrumentation.ts": "export {};\n",
  "src/shared/config.ts": "export const site = 'fixture';\n",
  "app/page.tsx": [
    'import { Hero } from "@evinvest/kitstart";',
    "export default function Page() { return Hero(); }",
    "",
  ].join("\n"),
  "node_modules/@evinvest/kitstart/package.json": JSON.stringify({ exports: { ".": { import: "./dist/index.js" } } }),
  "node_modules/@evinvest/kitstart/dist/index.js": [
    'import { Button } from "@evinvest/uikit";',
    'export function Hero() { return Button("hero"); }',
    "",
  ].join("\n"),
  "node_modules/@evinvest/uikit/package.json": JSON.stringify({ exports: { ".": { import: "./dist/index.js" } } }),
  "node_modules/@evinvest/uikit/dist/index.js": [
    'export { Button } from "./components/button.js";',
    'export { Dialog } from "./components/dialog.js";',
    "",
  ].join("\n"),
  "node_modules/@evinvest/uikit/dist/components/button.js": [
    'import { cn } from "../lib/cn.js";',
    'export function Button(extra) { return cn("px-4 bg-primary", extra); }',
    "",
  ].join("\n"),
  "node_modules/@evinvest/uikit/dist/components/dialog.js": 'export function Dialog() { return "fixed inset-0"; }\n',
  "node_modules/@evinvest/uikit/dist/lib/cn.js": 'export const cn = (...c) => c.join(" ");\n',
  "node_modules/@evinvest/marketing/package.json": JSON.stringify({ exports: { ".": { import: "./dist/index.js" } } }),
  "node_modules/@evinvest/marketing/dist/index.js": 'export const track = () => "marketing";\n',
};

function write(dir: string, path: string, content: string): void {
  mkdirSync(dirname(join(dir, path)), { recursive: true });
  writeFileSync(join(dir, path), content);
}

describe("a committed sources list that was not regenerated", () => {
  let fixture: string;

  // As if `npm run css-sources` had been run and its output committed.
  beforeEach(() => {
    fixture = mkdtempSync(join(tmpdir(), "aquafix-css-sources-"));
    for (const [path, content] of Object.entries(LANDING)) write(fixture, path, content);
    write(fixture, OUTPUT, renderSources(fixture));
  });

  afterEach(() => {
    rmSync(fixture, { recursive: true, force: true });
  });

  it("lists only the uikit files the fixture reaches, and passes while nothing changed", () => {
    expect(readFileSync(join(fixture, OUTPUT), "utf8")).toBe(
      [
        "/* GENERATED by scripts/css-sources.ts from the app's imports — do not edit by",
        " * hand; run `npm run css-sources` after bumping @evinvest/uikit, marketing or",
        " * kitstart, or importing something new of theirs. */",
        '@source "../node_modules/@evinvest/uikit/dist/components/button.js";',
        '@source "../node_modules/@evinvest/uikit/dist/lib/cn.js";',
        "",
      ].join("\n"),
    );
    expectSourcesCurrent(fixture);
  });

  it("fails, naming the command, when the app imports a uikit component it did not reach before", () => {
    write(
      fixture,
      "src/widgets/confirm.tsx",
      ['import { Dialog } from "@evinvest/uikit";', "export const Confirm = () => Dialog();", ""].join("\n"),
    );

    expect(renderSources(fixture)).toContain('@source "../node_modules/@evinvest/uikit/dist/components/dialog.js";');
    expect(() => expectSourcesCurrent(fixture)).toThrow("run `npm run css-sources`");
  });

  it("fails, naming the command, when a uikit bump makes a reached component import a new file", () => {
    write(
      fixture,
      "node_modules/@evinvest/uikit/dist/components/button.js",
      [
        'import { cn } from "../lib/cn.js";',
        'import { Spinner } from "./spinner.js";',
        'export function Button(extra) { return cn("px-4 bg-primary", extra, Spinner()); }',
        "",
      ].join("\n"),
    );
    write(fixture, "node_modules/@evinvest/uikit/dist/components/spinner.js", 'export const Spinner = () => "animate-spin";\n');

    expect(renderSources(fixture)).toContain('@source "../node_modules/@evinvest/uikit/dist/components/spinner.js";');
    expect(() => expectSourcesCurrent(fixture)).toThrow("run `npm run css-sources`");
  });

  it("fails, naming the command, when a kitstart bump makes its widget reach another uikit component", () => {
    write(
      fixture,
      "node_modules/@evinvest/kitstart/dist/index.js",
      [
        'import { Button, Dialog } from "@evinvest/uikit";',
        'export function Hero() { return Button("hero") + Dialog(); }',
        "",
      ].join("\n"),
    );

    expect(renderSources(fixture)).toContain('@source "../node_modules/@evinvest/uikit/dist/components/dialog.js";');
    expect(() => expectSourcesCurrent(fixture)).toThrow("run `npm run css-sources`");
  });
});
