// Cuts the web variants of `assets/photos/*.jpg` — AVIF and WebP at the widths
// the page lays them out at — into `assets/photos/web/`, and writes
// `src/shared/assets/photos.ts`, the module that imports them (so Next
// fingerprints each file) and spells their `srcset`s.
//
// Both outputs are committed: the Nix build runs no image encoder. Rerun after
// touching a photo or a width below; `tests/photos.test.ts` fails when the
// module no longer matches this plan.
//
//   nix shell nixpkgs#vips -c npm run photos
//
// Plain `node` runs it (type stripping), so it imports nothing but builtins.
import { execFileSync } from "node:child_process";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

interface Cut {
  /** Output name stem; the file is `<stem>-<width>.<format>`. */
  stem: string;
  source: string;
  widths: number[];
  /** A crop of the source, in source pixels, taken before resizing. */
  crop?: { left: number; top: number; width: number; height: number };
}

/**
 * The plan. Widths never exceed the (cropped) source: an upscale is bytes
 * with no detail in them.
 */
export const CUTS: Cut[] = [
  // Full-bleed from `md` up; the source is 1536 px wide.
  { stem: "hero-wide", source: "hero-wide.jpg", widths: [1024, 1536] },
  // Below `md` the hero is ≥580 px tall and `object-cover` scales the 1536×654
  // frame to that height, so a phone shows ~400 source px around 72 % across.
  // This crop keeps the region every width up to 767 px can show (≤865 px) at
  // the same density — the phone stops paying for the two thirds it never sees.
  { stem: "hero-mobile", source: "hero-wide.jpg", widths: [900], crop: { left: 458, top: 0, width: 900, height: 654 } },
  // Square thumbnails: ~180 css px in two columns on a phone, ~250 in four on
  // desktop; the popover shows the same file at full measure width.
  { stem: "job-under-sink", source: "job-under-sink.jpg", widths: [400, 800] },
  { stem: "job-tap-shower", source: "job-tap-shower.jpg", widths: [400, 800] },
  { stem: "job-hot-water", source: "job-hot-water.jpg", widths: [400, 800] },
  { stem: "job-pipe-repair", source: "job-pipe-repair.jpg", widths: [400, 571] },
];

export const FORMATS = [
  // Quality picked by eye against the jpg at 100 %; AVIF's scale runs lower.
  { ext: "avif", type: "image/avif", options: "[Q=52,effort=6,strip]" },
  { ext: "webp", type: "image/webp", options: "[Q=74,effort=6,strip]" },
] as const;

const PHOTOS = "assets/photos";
const WEB = join(PHOTOS, "web");
const MODULE = "src/shared/assets/photos.ts";

const ident = (s: string) => s.replace(/[^a-z0-9]+/gi, "_");

/** The module text for {@link CUTS} — also what the test compares against. */
export function renderModule(): string {
  const imports: string[] = [];
  const sets: string[] = [];
  for (const cut of CUTS) {
    const byFormat = FORMATS.map(f => {
      const parts = cut.widths.map(w => {
        const name = ident(`${cut.stem}_${w}_${f.ext}`);
        imports.push(`import ${name} from "../../../${WEB}/${cut.stem}-${w}.${f.ext}";`);
        return `\`\${${name}.src} ${w}w\``;
      });
      return `    ${f.ext}: [${parts.join(", ")}].join(", "),`;
    });
    sets.push(`  "${cut.stem}": {\n${byFormat.join("\n")}\n  },`);
  }
  return [
    "// GENERATED by scripts/photos.ts from its CUTS table — do not edit by hand;",
    "// change the table and run `nix shell nixpkgs#vips -c npm run photos`.",
    ...imports,
    "",
    "/** Each photo's `srcset` per format, for a `<picture>`'s `<source>`s. */",
    "export const PHOTO_SETS = {",
    ...sets,
    "} as const;",
    "",
    "export type PhotoStem = keyof typeof PHOTO_SETS;",
    "",
  ].join("\n");
}

function cut(c: Cut, width: number, ext: string, options: string) {
  const src = join(PHOTOS, c.source);
  const out = join(WEB, `${c.stem}-${width}.${ext}`);
  let input = src;
  if (c.crop) {
    input = join(WEB, `.${c.stem}-crop.v`);
    const { left, top, width: w, height: h } = c.crop;
    execFileSync("vips", ["extract_area", src, input, String(left), String(top), String(w), String(h)]);
  }
  execFileSync("vips", ["thumbnail", input, `${out}${options}`, String(width), "--size", "down"]);
  if (c.crop) rmSync(input);
}

function main() {
  rmSync(WEB, { recursive: true, force: true });
  mkdirSync(WEB, { recursive: true });
  for (const c of CUTS) for (const w of c.widths) for (const f of FORMATS) cut(c, w, f.ext, f.options);
  mkdirSync("src/shared/assets", { recursive: true });
  writeFileSync(MODULE, renderModule());
  console.log(`✔ ${WEB}/ and ${MODULE}`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
