// GENERATED by scripts/photos.ts from its CUTS table — do not edit by hand;
// change the table and run `nix shell nixpkgs#vips -c npm run photos`.
import hero_wide_1024_avif from "../../../assets/photos/web/hero-wide-1024.avif";
import hero_wide_1536_avif from "../../../assets/photos/web/hero-wide-1536.avif";
import hero_wide_1024_webp from "../../../assets/photos/web/hero-wide-1024.webp";
import hero_wide_1536_webp from "../../../assets/photos/web/hero-wide-1536.webp";
import hero_mobile_900_avif from "../../../assets/photos/web/hero-mobile-900.avif";
import hero_mobile_900_webp from "../../../assets/photos/web/hero-mobile-900.webp";
import job_under_sink_400_avif from "../../../assets/photos/web/job-under-sink-400.avif";
import job_under_sink_800_avif from "../../../assets/photos/web/job-under-sink-800.avif";
import job_under_sink_400_webp from "../../../assets/photos/web/job-under-sink-400.webp";
import job_under_sink_800_webp from "../../../assets/photos/web/job-under-sink-800.webp";
import job_tap_shower_400_avif from "../../../assets/photos/web/job-tap-shower-400.avif";
import job_tap_shower_800_avif from "../../../assets/photos/web/job-tap-shower-800.avif";
import job_tap_shower_400_webp from "../../../assets/photos/web/job-tap-shower-400.webp";
import job_tap_shower_800_webp from "../../../assets/photos/web/job-tap-shower-800.webp";
import job_hot_water_400_avif from "../../../assets/photos/web/job-hot-water-400.avif";
import job_hot_water_800_avif from "../../../assets/photos/web/job-hot-water-800.avif";
import job_hot_water_400_webp from "../../../assets/photos/web/job-hot-water-400.webp";
import job_hot_water_800_webp from "../../../assets/photos/web/job-hot-water-800.webp";
import job_pipe_repair_400_avif from "../../../assets/photos/web/job-pipe-repair-400.avif";
import job_pipe_repair_571_avif from "../../../assets/photos/web/job-pipe-repair-571.avif";
import job_pipe_repair_400_webp from "../../../assets/photos/web/job-pipe-repair-400.webp";
import job_pipe_repair_571_webp from "../../../assets/photos/web/job-pipe-repair-571.webp";

/** Each photo's `srcset` per format, for a `<picture>`'s `<source>`s. */
export const PHOTO_SETS = {
  "hero-wide": {
    avif: [`${hero_wide_1024_avif.src} 1024w`, `${hero_wide_1536_avif.src} 1536w`].join(", "),
    webp: [`${hero_wide_1024_webp.src} 1024w`, `${hero_wide_1536_webp.src} 1536w`].join(", "),
  },
  "hero-mobile": {
    avif: [`${hero_mobile_900_avif.src} 900w`].join(", "),
    webp: [`${hero_mobile_900_webp.src} 900w`].join(", "),
  },
  "job-under-sink": {
    avif: [`${job_under_sink_400_avif.src} 400w`, `${job_under_sink_800_avif.src} 800w`].join(", "),
    webp: [`${job_under_sink_400_webp.src} 400w`, `${job_under_sink_800_webp.src} 800w`].join(", "),
  },
  "job-tap-shower": {
    avif: [`${job_tap_shower_400_avif.src} 400w`, `${job_tap_shower_800_avif.src} 800w`].join(", "),
    webp: [`${job_tap_shower_400_webp.src} 400w`, `${job_tap_shower_800_webp.src} 800w`].join(", "),
  },
  "job-hot-water": {
    avif: [`${job_hot_water_400_avif.src} 400w`, `${job_hot_water_800_avif.src} 800w`].join(", "),
    webp: [`${job_hot_water_400_webp.src} 400w`, `${job_hot_water_800_webp.src} 800w`].join(", "),
  },
  "job-pipe-repair": {
    avif: [`${job_pipe_repair_400_avif.src} 400w`, `${job_pipe_repair_571_avif.src} 571w`].join(", "),
    webp: [`${job_pipe_repair_400_webp.src} 400w`, `${job_pipe_repair_571_webp.src} 571w`].join(", "),
  },
} as const;

export type PhotoStem = keyof typeof PHOTO_SETS;
